name: "PEP8"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nose nose-exclude coverage coveralls pycodestyle
        pip install --progress-bar off .
    - name: Run unit tests
      run: |
        python setup.py nosetests
    - name: Check Python syntax
      run: |
        pycodestyle surfify --ignore="E121,E123,E126,E226,E24,E704,E402,E731,E722,E741,W503,W504,W605"
    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.7
      with:
        env_vars: OS,PYTHON
